name: train_diffusion_unet_timm
_target_: diffusion_policy.workspace.train_diffusion_unet_image_workspace.TrainDiffusionUnetImageWorkspace
task_name: umi
shape_meta:
  obs:
    camera0_rgb:
      shape:
      - 3
      - 224
      - 224
      horizon: 2
      latency_steps: 0
      down_sample_steps: 3
      type: rgb
      ignore_by_policy: false
    robot0_eef_pos:
      shape:
      - 3
      horizon: 2
      latency_steps: 0.0
      down_sample_steps: 3
      type: low_dim
      ignore_by_policy: false
    robot0_eef_rot_axis_angle:
      raw_shape:
      - 3
      shape:
      - 6
      horizon: 2
      latency_steps: 0.0
      down_sample_steps: 3
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: false
    robot0_gripper_width:
      shape:
      - 1
      horizon: 2
      latency_steps: 0.0
      down_sample_steps: 3
      type: low_dim
      ignore_by_policy: false
    robot0_eef_rot_axis_angle_wrt_start:
      raw_shape:
      - 3
      shape:
      - 6
      horizon: 2
      latency_steps: 0.0
      down_sample_steps: 3
      type: low_dim
      ignore_by_policy: false
  action:
    shape:
    - 10
    horizon: 16
    latency_steps: 0
    down_sample_steps: 3
    rotation_rep: rotation_6d
exp_name: default
n_action_steps: 8
policy:
  _target_: diffusion_policy.policy.diffusion_unet_timm_policy.DiffusionUnetTimmPolicy
  shape_meta:
    obs:
      camera0_rgb:
        shape:
        - 3
        - 224
        - 224
        horizon: 2
        latency_steps: 0
        down_sample_steps: 3
        type: rgb
        ignore_by_policy: false
      robot0_eef_pos:
        shape:
        - 3
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
      robot0_eef_rot_axis_angle:
        raw_shape:
        - 3
        shape:
        - 6
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        rotation_rep: rotation_6d
        ignore_by_policy: false
      robot0_gripper_width:
        shape:
        - 1
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
      robot0_eef_rot_axis_angle_wrt_start:
        raw_shape:
        - 3
        shape:
        - 6
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
    action:
      shape:
      - 10
      horizon: 16
      latency_steps: 0
      down_sample_steps: 3
      rotation_rep: rotation_6d
  noise_scheduler:
    _target_: diffusers.DDIMScheduler
    num_train_timesteps: 50
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: true
    set_alpha_to_one: true
    steps_offset: 0
    prediction_type: epsilon
  obs_encoder:
    _target_: diffusion_policy.model.vision.timm_obs_encoder.TimmObsEncoder
    shape_meta:
      obs:
        camera0_rgb:
          shape:
          - 3
          - 224
          - 224
          horizon: 2
          latency_steps: 0
          down_sample_steps: 3
          type: rgb
          ignore_by_policy: false
        robot0_eef_pos:
          shape:
          - 3
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
        robot0_eef_rot_axis_angle:
          raw_shape:
          - 3
          shape:
          - 6
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          rotation_rep: rotation_6d
          ignore_by_policy: false
        robot0_gripper_width:
          shape:
          - 1
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
        robot0_eef_rot_axis_angle_wrt_start:
          raw_shape:
          - 3
          shape:
          - 6
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
      action:
        shape:
        - 10
        horizon: 16
        latency_steps: 0
        down_sample_steps: 3
        rotation_rep: rotation_6d
    model_name: vit_base_patch16_clip_224.openai
    pretrained: true
    frozen: false
    global_pool: ''
    feature_aggregation: attention_pool_2d
    position_encording: sinusoidal
    downsample_ratio: 32
    transforms:
    - type: RandomCrop
      ratio: 0.95
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.3
      contrast: 0.4
      saturation: 0.5
      hue: 0.08
    use_group_norm: true
    share_rgb_model: false
    imagenet_norm: true
  num_inference_steps: 16
  obs_as_global_cond: true
  diffusion_step_embed_dim: 128
  down_dims:
  - 256
  - 512
  - 1024
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: true
  input_pertub: 0.1
  train_diffusion_n_samples: 1
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999
dataloader:
  batch_size: 16
  num_workers: 8
  shuffle: true
  pin_memory: true
  persistent_workers: true
val_dataloader:
  batch_size: 16
  num_workers: 8
  shuffle: false
  pin_memory: true
  persistent_workers: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  weight_decay: 1.0e-06
training:
  device: cuda:0
  seed: 42
  debug: false
  resume: false
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  num_epochs: 120
  gradient_accumulate_every: 1
  use_ema: true
  freeze_encoder: false
  rollout_every: 10
  checkpoint_every: 10
  val_every: 1
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0
logging:
  project: umi
  resume: false
  mode: online
  name: 2025.01.03-09.20.03_train_diffusion_unet_timm_umi
  tags:
  - train_diffusion_unet_timm
  - umi
  - default
  id: null
  group: null
checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 20
    format_str: epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt
  save_last_ckpt: true
  save_last_snapshot: false
multi_run:
  run_dir: data/outputs/2025.01.03/09.20.03_train_diffusion_unet_timm_umi
  wandb_name_base: 2025.01.03-09.20.03_train_diffusion_unet_timm_umi
task:
  name: umi
  camera_obs_latency: 0.125
  robot_obs_latency: 0.0001
  gripper_obs_latency: 0.02
  dataset_frequeny: 0
  obs_down_sample_steps: 3
  low_dim_obs_horizon: 2
  img_obs_horizon: 2
  action_horizon: 16
  ignore_proprioception: false
  shape_meta:
    obs:
      camera0_rgb:
        shape:
        - 3
        - 224
        - 224
        horizon: 2
        latency_steps: 0
        down_sample_steps: 3
        type: rgb
        ignore_by_policy: false
      robot0_eef_pos:
        shape:
        - 3
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
      robot0_eef_rot_axis_angle:
        raw_shape:
        - 3
        shape:
        - 6
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        rotation_rep: rotation_6d
        ignore_by_policy: false
      robot0_gripper_width:
        shape:
        - 1
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
      robot0_eef_rot_axis_angle_wrt_start:
        raw_shape:
        - 3
        shape:
        - 6
        horizon: 2
        latency_steps: 0.0
        down_sample_steps: 3
        type: low_dim
        ignore_by_policy: false
    action:
      shape:
      - 10
      horizon: 16
      latency_steps: 0
      down_sample_steps: 3
      rotation_rep: rotation_6d
  task_name: umi
  dataset_path: dyros_example/dataset.zarr.zip
  pose_repr:
    obs_pose_repr: relative
    action_pose_repr: relative
  env_runner:
    _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner
  dataset:
    _target_: diffusion_policy.dataset.umi_dataset.UmiDataset
    shape_meta:
      obs:
        camera0_rgb:
          shape:
          - 3
          - 224
          - 224
          horizon: 2
          latency_steps: 0
          down_sample_steps: 3
          type: rgb
          ignore_by_policy: false
        robot0_eef_pos:
          shape:
          - 3
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
        robot0_eef_rot_axis_angle:
          raw_shape:
          - 3
          shape:
          - 6
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          rotation_rep: rotation_6d
          ignore_by_policy: false
        robot0_gripper_width:
          shape:
          - 1
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
        robot0_eef_rot_axis_angle_wrt_start:
          raw_shape:
          - 3
          shape:
          - 6
          horizon: 2
          latency_steps: 0.0
          down_sample_steps: 3
          type: low_dim
          ignore_by_policy: false
      action:
        shape:
        - 10
        horizon: 16
        latency_steps: 0
        down_sample_steps: 3
        rotation_rep: rotation_6d
    dataset_path: dyros_example/dataset.zarr.zip
    cache_dir: null
    pose_repr:
      obs_pose_repr: relative
      action_pose_repr: relative
    action_padding: false
    temporally_independent_normalization: false
    repeat_frame_prob: 0.0
    max_duration: null
    seed: 42
    val_ratio: 0.05
